CREATE TABLE METACARD_STORE (
    ID VARCHAR(255) PRIMARY KEY,
    UPDATE_DT BIGINT NOT NULL,
    METACARD_DATA TEXT NOT NULL
);

CREATE INDEX METACARD_STORE_DATE_IDX ON METACARD_STORE (
    UPDATE_DT DESC
);