version: '3.5'
services:
  zk1:
    image: zookeeper:${docker.zookeeper.version}
    restart: always
    ports:
    - "0.0.0.0:${docker.zookeeper.port.1}:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
      JVMFLAGS: "-Xms48m -Xmx128m"
    hostname: zk1
  zk2:
    image: zookeeper:${docker.zookeeper.version}
    restart: always
    ports:
    - "0.0.0.0:${docker.zookeeper.port.2}:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
      JVMFLAGS: "-Xms48m -Xmx128m"
    hostname: zk2
  zk3:
    image: zookeeper:${docker.zookeeper.version}
    restart: always
    ports:
    - "0.0.0.0:${docker.zookeeper.port.3}:2181"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
      JVMFLAGS: "-Xms48m -Xmx128m"
    hostname: zk3
  solr1:
    image: codice/ddf-solr:${project.version}
    restart: always
    ports:
    - ${docker.solr.port.1}:${docker.solr.port.1}
    command: ["/opt/solr/bin/solr",
              "start",
              "-f",
              "-cloud",
              "-z", "zk1:2181,zk2:2181,zk3:2181",
              "-p", "${docker.solr.port.1}", "-h", "solr1"]
    hostname: solr1
    volumes:
    - type: bind
      source: ${docker.solr.backup.directory.local}
      target: ${docker.solr.backup.directory.target}
  solr2:
    image: codice/ddf-solr:${project.version}
    restart: always
    ports:
    - ${docker.solr.port.2}:${docker.solr.port.2}
    command: ["/opt/solr/bin/solr",
              "start",
              "-f",
              "-cloud",
              "-z", "zk1:2181,zk2:2181,zk3:2181",
              "-p", "${docker.solr.port.2}", "-h", "solr2"]
    hostname: solr2
    volumes:
    - type: bind
      source: ${docker.solr.backup.directory.local}
      target: ${docker.solr.backup.directory.target}
  solr3:
    image: codice/ddf-solr:${project.version}
    restart: always
    ports:
    - ${docker.solr.port.3}:${docker.solr.port.3}
    command: ["/opt/solr/bin/solr",
              "start",
              "-f",
              "-cloud",
              "-z", "zk1:2181,zk2:2181,zk3:2181",
              "-p", "${docker.solr.port.3}", "-h", "solr3"]
    hostname: solr3
    volumes:
    - type: bind
      source: ${docker.solr.backup.directory.local}
      target: ${docker.solr.backup.directory.target}

  ddf:
    container_name: ddf
    stdin_open: true
    image: codice/ddf:${project.version}
    ports:
    - "8993:8993"
    - "5005:5005"
    - "8101:8101"                         # can connect to the client via "ssh admin@localhost -p 8101"
    - "8181:8181"
    environment:
      INSTALL_PROFILE: standard
      SSH_ENABLED: 'true'                   # Keep the karaf ssh port active (supports using client during runtime)
      SOLR_ZK_HOSTS: "zk1:2181,zk2:2181,zk3:2181"
      JAVA_MAX_MEM: 4
    hostname: localhost
    volumes:
    - type: bind          # Support solr cloud backups
      source: ${docker.solr.backup.directory.local}
      target: ${docker.solr.backup.directory.target}
    - type: bind          # Support using bundle:watch
      source: ${HOME}/.m2
      target: /root/.m2
